# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
paths:
  .github/workflows/ci.yml:
    ignore:
      - property "vendor" is not defined in object type.+
      - property "release" is not defined in object type.+
