# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'fix-testing-image-tag'
description: 'Fix testing image tag'
author: 'vicamo'

inputs:
  release:
    description: >-
      Specify the target release to run the workflow. By default, everything
      will run on the 'unstable' suite. The following releases are currently
      supported:

      * experimental

      * unstable (default)

      * testing

      * stable
    default: 'unstable'

runs:
  using: 'composite'
  steps:
    - name: Modify action metadata for testing
      run: |
        sed -e 's,^\(  image: ghcr.io/${{ github.repository_owner }}\)/gbp:.*$,\1/staging:${{ github.run_id }}-gbp-${{ env.DEFAULT_RELEASE }},' \
            -i actions/extract-source/action.yml

        grep -nr ${{ github.run_id }} actions
