# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'dummy'
description: 'dummy action'
author: 'vicamo'

inputs:
  image:
    description: Target docker image to launch.
    default: 'ghcr.io/hustle-ci/base:latest'
  include_env_match:
    description: >-
      Regular expression to match additional environment variables to pass into
      the launched container.
    default: ''
  docker_args:
    description: Additional arguments to launch the docker image.
    default: ''
  image_cmds:
    description: Additional command arguments for the docker image.
    default: ''

  source_path:
    description: >-
      Relative path to GITHUB_WORKSPACE where source root is stored. Default is
      `GITHUB_WORKSPACE`.
    default: ''
  output_path:
    description: >-
      Relative path to GITHUB_WORKSPACE where built artifacts should be stored.
      Default is `source_path`/debian/output.
    default: ''

outputs:
  source_path:
    description: >-
      The actual `source_path` used.
  output_path:
    description: >-
      The actual `output_path` used.

runs:
  using: 'docker'
  image: 'ghcr.io/hustle-ci/launcher:latest'
  args:
    - '/start.sh'
    - '--entrypoint'
    - '/usr/local/bin/dummy.sh'
    - '--'
    - ${{ inputs.image }}
