# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'build image'
on:
  workflow_call:
    inputs:
      vendor:
        description: 'Distribution vendor. Currently supports only debian.'
        type: string
        default: 'debian'
      release:
        description: 'Distribution release name, e.g. unstable for debian.'
        type: string
        default: 'unstable'
      target:
        description: 'Target image stage.'
        type: string
        required: true
      platforms:
        description: 'Comma-separated platform names for multiple architectures build.'
        type: string
        default: 'linux/amd64'
      tag_prefix:
        description: 'String prefix for built image tag.'
        type: string
        required: true

env:
  IMAGE_VERSION: '1'

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ inputs.platforms != 'linux/amd64' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.description=${{ inputs.target }} image for ${{ inputs.vendor }}:${{ inputs.release }}
            org.opencontainers.image.licenses=FSFAP
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.version=${{ env.IMAGE_VERSION }}
          images: ghcr.io/${{ github.repository_owner }}/staging
          flavor: |
            latest=false
            prefix=${{ inputs.tag_prefix }}
          tags: |
            ${{ inputs.target }}-${{ inputs.release }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: 'images'
          build-args: |
              BASE_IMAGE=${{ inputs.vendor }}:${{ inputs.release }}
              VENDOR=${{ inputs.vendor }}
              RELEASE=${{ inputs.release }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          outputs: type=image,push=true,annotation-index.org.opencontainers.image.description=${{ inputs.target }} image for ${{ inputs.vendor }}:${{ inputs.release }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ steps.meta.outputs.tags }}
          target: ${{ inputs.target }}

