# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'CI'
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - 'README.*'
  pull_request:
    paths-ignore:
      - LICENSE
      - 'README.*'

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Install prerequisites'
        run: |
          sudo apt-get update --quiet
          sudo apt-get install --no-install-recommends -y \
              licensecheck

      - name: 'Check license'
        run: |
          PROBLEMS=0

          BAD_FILES=$(licensecheck -r . | grep -Ev '(README.md)'| grep UNKNOWN) || true
          if [ -n "${BAD_FILES}" ]; then
            echo "ERROR: Missing license statement in the following files:"
            echo "$BAD_FILES"
            PROBLEMS=$(($PROBLEMS + 1))
          fi

          exit $PROBLEMS
