# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'CI'
on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - 'README.*'
  pull_request:
    paths-ignore:
      - LICENSE
      - 'README.*'

env:
  DEFAULT_RELEASE: 'unstable'

jobs:
  base-images:
    strategy:
      matrix:
        include:
          - release: 'experimental'
            platforms: 'linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v5,linux/mips64le,linux/riscv64,linux/ppc64le,linux/s390x'
          - release: 'unstable'
            platforms: 'linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v5,linux/mips64le,linux/riscv64,linux/ppc64le,linux/s390x'
          - release: 'testing'
            platforms: 'linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v5,linux/mips64le,linux/ppc64le,linux/s390x'
          - release: 'stable'
            platforms: 'linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7,linux/arm/v5,linux/mips64le,linux/ppc64le,linux/s390x'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yml
    with:
      vendor: 'debian'
      release: ${{ matrix.release }}
      target: 'base'
      platforms: ${{ matrix.platforms }}
      tag_prefix: ${{ github.run_id }}-

  check-license:
    needs:
      - base-images
    uses: ./.github/workflows/check-license.yml
    with:
      # env context not allowed here, so put hard-coded string instead of env.DEFAULT_RELEASE
      image: ghcr.io/${{ github.repository_owner }}/staging:${{ github.run_id }}-base-unstable

  latest-amd64-images:
    needs:
      # Depend on local tests before going further
      - check-license
    strategy:
      matrix:
        target:
          - 'gbp'
        release:
          # env context not allowed here, so put hard-coded string instead of env.DEFAULT_RELEASE
          - 'unstable'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-image.yml
    with:
      vendor: 'debian'
      release: ${{ matrix.release }}
      target: ${{ matrix.target }}
      tag_prefix: ${{ github.run_id }}-

  prune-staging-images:
    needs:
      - base-images
      - latest-amd64-images
      - check-license
    if: ${{ always() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Prune staging images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: ${{ github.repository_owner }}
          container: 'staging'
          dry-run: false
          prune-tags-regexes: |
            ^${{ github.run_id }}-
          prune-untagged: true
