# Copyright 2023 You-Sheng Yang and others
# SPDX-License-Identifier: FSFAP
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
---
name: 'test per release'
on:
  workflow_call:
    inputs:
      release:
        description: 'Distribution release name, e.g. unstable for debian.'
        type: string
        default: 'unstable'
      default_release:
        description: >-
          The default release to be used for actions with no release variants.
          Empty string as an alias to `inputs.release`.
        type: string
        default: ''

env:
  ARCHIVED_SOURCE_TAR_SUFFIX: .source.tar.gz

jobs:
  extract-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/clone-test-project
        id: clone
        with:
          release: ${{ inputs.release }}

      - name: Extract source package
        id: extract
        uses: ./actions/extract-source
        with:
          image: ${{ format('ghcr.io/{0}/staging:{1}-gbp-{2}', github.repository_owner, github.run_id, inputs.default_release) }}
          source_path: ${{ steps.clone.outputs.source_path }}
          output_path: ${{ hashFiles('action.yml', 'actions/*/action.yml') }}

      # Github ations/upload-artifact does not retain artifact permissions.
      # See: https://github.com/actions/upload-artifact/issues/38
      - name: Archive built source directory
        run: |
          cd ${{ steps.extract.outputs.output_path }}

          name=${{ steps.extract.outputs.built_origtar }}
          name="${name%.orig.*}${ARCHIVED_SOURCE_TAR_SUFFIX}"
          tar acpf "${name}" -C source .

          rm -rf source

      - name: Upload source package
        # Don't use v4 unless https://github.com/actions/download-artifact/issues/249 solved.
        uses: actions/upload-artifact@v3
        with:
          name: per-action-source-${{ inputs.release }}
          path: |
            ${{ steps.extract.outputs.output_path }}
          if-no-files-found: error
